//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeProjectEntities : DbContext
    {
        public EmployeeProjectEntities()
            : base("name=EmployeeProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dtable> Dtables { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<EmpType> EmpTypes { get; set; }
        public virtual DbSet<LoginPage> LoginPages { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<Dept> Depts { get; set; }
        public virtual DbSet<SubDept> SubDepts { get; set; }
        public virtual DbSet<PromoteEmployee> PromoteEmployees { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<TransferEmployee> TransferEmployees { get; set; }
        public virtual DbSet<ReportingManager> ReportingManagers { get; set; }
    }
}
