//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferEmployee
    {
        public int ID { get; set; }
        public Nullable<int> SelectEmployee { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
